import { test, expect } from "@playwright/test";
import { adminFixture } from "../fixtures/admin";
import { infrastructureFixture, signIn } from "../fixtures/infrastructure";
import { id, overview, presentation } from "../fixtures/dashboard";

test("application form keeps an empty secret and deletion requires confirmation", async ({ page }) => {
  await adminFixture(page);
  const services: Record<string, unknown>[] = [];
  const writes: { method: string; body: Record<string, unknown> | null }[] = [];
  let conflict = false;
  const at = new Date().toISOString();
  await page.route("**/api/monitoring/external-services/*", async route => {
    const request = route.request();
    if (request.method() === "GET") return route.fulfill({ json: { data: { serviceId: services[0]?.id, range: "24h", points: [{ checkedAt: at, reason: 0, latencyMs: 80 }], summary: { currentLatencyMs: 80, averageLatencyMs: 80, uptime24h: { available: 1, total: 1 }, uptime7d: { available: 1, total: 1 }, uptime30d: { available: 1, total: 1 } } } } });
    if (request.method() === "DELETE") { writes.push({ method: "DELETE", body: null }); services.pop(); return route.fulfill({ status: 204 }); }
    const body = request.postDataJSON() as Record<string, unknown>;
    writes.push({ method: request.method(), body });
    if (conflict) return route.fulfill({ status: 409, json: { error: { code: "revision_conflict" } } });
    const current = services[0];
    const next: Record<string, unknown> = { ...current, ...body, revision: Number(current.revision) + 1, secretConfigured: body.secret === null ? false : body.secret ? true : current.secretConfigured, updatedAt: at };
    delete next.secret; delete next.expectedRevision;
    services[0] = next;
    return route.fulfill({ json: { data: next } });
  });
  await page.route("**/api/monitoring/external-services/*/history*", async route => route.fulfill({ json: { data: { serviceId: services[0]?.id, range: "24h", points: [{ checkedAt: at, reason: 0, latencyMs: 80 }], summary: { currentLatencyMs: 80, averageLatencyMs: 80, uptime24h: { available: 1, total: 1 }, uptime7d: { available: 1, total: 1 }, uptime30d: { available: 1, total: 1 } } } } }));
  await page.route("**/api/monitoring/external-services", async route => {
    if (route.request().method() === "GET") return route.fulfill({ json: { data: services } });
    const body = route.request().postDataJSON() as Record<string, unknown>;
    writes.push({ method: "POST", body });
    const saved: Record<string, unknown> = { ...body, id: id(8), revision: 1, secretConfigured: Boolean(body.secret), createdAt: at, updatedAt: at, uptime: { reason: 0, latencyMs: 80, checkedAt: at, uptime24h: { available: 1, total: 1 }, strip: [0] } };
    delete saved.secret;
    services.push(saved);
    return route.fulfill({ status: 201, json: { data: saved } });
  });
  await signIn(page);
  await page.setViewportSize({ width: 390, height: 800 });
  await page.goto("/admin/aplicacoes");
  const overviewLink = page.getByRole("link", { name: "Visão geral", exact: true });
  const servicesLink = page.getByRole("link", { name: "Serviços", exact: true });
  const overviewBox = await overviewLink.boundingBox();
  const servicesBox = await servicesLink.boundingBox();
  expect(overviewBox && servicesBox && servicesBox.x > overviewBox.x && Math.abs(servicesBox.y - overviewBox.y) < 8).toBe(true);
  await page.getByRole("button", { name: "Nova aplicação", exact: true }).click();
  await page.getByLabel("Nome", { exact: true }).fill("API externa");
  await page.getByLabel("URL", { exact: true }).fill("https://api.example.test/health");
  await page.getByLabel("Autenticação", { exact: true }).selectOption("header");
  await page.getByLabel("Nome do cabeçalho", { exact: true }).fill("Authorization");
  await page.getByLabel("Segredo", { exact: true }).fill("segredo-inicial");
  await page.getByRole("button", { name: "Salvar aplicação", exact: true }).click();
  await expect(page.locator(".app-monitor-list")).toContainText("API externa");
  const addBox = await page.getByRole("button", { name: "Nova aplicação", exact: true }).boundingBox();
  const listBox = await page.locator(".app-monitor-list").boundingBox();
  expect(addBox && listBox && addBox.y < listBox.y).toBe(true);
  await expect(page.locator(".app-monitor-detail")).toContainText("No ar");
  await expect(page.locator(".app-monitor-detail .uptime-track rect")).toHaveCount(40);
  await expect(page.locator(".app-monitor-detail .uptime-track rect[opacity='0.35']")).toHaveCount(39);
  expect(writes[0].body?.secret).toBe("segredo-inicial");
  await page.getByRole("button", { name: "Editar", exact: true }).click();
  await page.getByLabel("Nome", { exact: true }).fill("API externa editada");
  await page.getByRole("button", { name: "Salvar aplicação", exact: true }).click();
  await expect.poll(() => writes.length).toBe(2);
  expect(writes[1].method).toBe("PATCH");
  expect(writes[1].body).not.toHaveProperty("secret");
  await expect(page.locator(".app-monitor-list")).toContainText("API externa editada");
  conflict = true;
  await page.getByRole("button", { name: "Editar", exact: true }).click();
  await page.getByLabel("Nome", { exact: true }).fill("Rascunho mantido");
  await page.getByRole("button", { name: "Salvar aplicação", exact: true }).click();
  await expect(page.locator(".admin-error[role=alert]")).toContainText("rascunho foi mantido");
  await expect(page.getByLabel("Nome", { exact: true })).toHaveValue("Rascunho mantido");
  conflict = false;
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  const writesBeforePause = writes.length;
  await page.getByRole("button", { name: "Pausar", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("deixa de consultar esta URL");
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  expect(writes).toHaveLength(writesBeforePause);
  await expect(page.locator(".app-monitor-detail")).toContainText("No ar");
  await page.getByRole("button", { name: "Pausar", exact: true }).click();
  await page.getByRole("button", { name: "Pausar aplicação", exact: true }).click();
  await expect(page.locator(".app-presence")).toContainText("Pausado");
  await expect(page.locator(".app-monitor-list")).toContainText("Pausada");
  await expect(page.locator(".app-monitor-detail .uptime-track rect[opacity='0.35']")).toHaveCount(40);
  await expect(page.locator(".app-monitor-list .uptime-strip rect[opacity='0.35']")).toHaveCount(40);
  expect(writes.at(-1)?.body?.enabled).toBe(false);
  await page.getByRole("button", { name: "Remover", exact: true }).click();
  await page.getByRole("button", { name: "Cancelar", exact: true }).click();
  expect(writes.filter(item => item.method === "DELETE")).toHaveLength(0);
  await page.getByRole("button", { name: "Remover", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Nenhum recurso do Zabbix será alterado.");
  await page.getByRole("button", { name: "Remover aplicação", exact: true }).click();
  await expect(page.locator(".app-monitor-list")).toContainText("Nenhuma aplicação cadastrada");
  expect(writes.filter(item => item.method === "DELETE")).toHaveLength(1);
});
test("probe cards keep the availability size and the uptime block scrolls inside the panel", async ({ page }) => {
  await infrastructureFixture(page);
  const document = presentation();
  const screen = document.screens[0];
  screen.blocks.push({ id: id(900), type: "uptime_list", enabled: true, width: "wide" });
  const body = overview(document);
  const checkedAt = new Date().toISOString();
  const probes = Array.from({ length: 8 }, (_, index) => ({ id: id(500 + index), displayName: index === 0 ? "API externa" : `Aplicação ${index}`, description: index === 0 ? "Portal" : null, serviceType: "API", displayOrder: index, critical: false, dashboardEnabled: index === 0, paused: false, progressStartedAt: null, reason: index === 3 ? 5 : 0, latencyMs: index === 3 ? null : 120, checkedAt, httpStatus: 200, certNotAfter: new Date(Date.now() + 10 * 86400000).toISOString(), uptime24h: { available: index === 3 ? 1 : 10, total: 10 }, strip: Array.from({ length: index === 0 ? 40 : 2 }, () => index === 3 ? 5 : 0) }));
  body.data.externalServices = probes.filter(item => item.dashboardEnabled);
  body.data.uptimeBoard = probes;
  body.data.blocks = body.data.blocks.map(block => block.type === "uptime_list" ? { ...block, data: probes, options: { sortBy: "name", sortDirection: "asc", visibleRows: 3 }, availability: "ready", stale: false } : block);
  const ranges: string[] = [];
  const registered = (probe: typeof probes[number], displayName: string) => ({ id: probe.id, revision: 1, secretConfigured: false, createdAt: checkedAt, updatedAt: checkedAt, displayName, description: probe.description, serviceType: "API", enabled: true, dashboardEnabled: probe.dashboardEnabled, critical: false, displayOrder: probe.displayOrder, method: "GET" as const, url: "https://api.example.test/health", successMode: "http_status" as const, expectedStatuses: [200], jsonPointer: null, expectedValue: null, bodyTemplate: null, authMode: "none" as const, headerName: null, timeoutMs: 5000, uptime: { reason: probe.reason, latencyMs: probe.latencyMs, checkedAt, uptime24h: probe.uptime24h, strip: probe.strip } });
  await page.route("**/api/monitoring/external-services", route => route.fulfill({ json: { data: [registered(probes[1], "Outra aplicação"), registered(probes[0], "API externa")] } }));
  await page.route("**/api/settings/presentation", route => route.fulfill({ json: { data: document, updatedAt: body.lastUpdated } }));
  await page.route("**/api/dashboard/overview*", route => route.fulfill({ json: body }));
  await page.route("**/api/monitoring/external-services/*/history*", route => {
    const range = new URL(route.request().url()).searchParams.get("range") ?? "";
    ranges.push(range);
    const points = range === "7d" ? [] : [{ checkedAt, reason: 0, latencyMs: 120 }, { checkedAt, reason: 5, latencyMs: null }];
    return route.fulfill({ json: { data: { serviceId: probes[0].id, range, points, summary: { currentLatencyMs: 120, averageLatencyMs: 120, uptime24h: { available: 1, total: 2 }, uptime7d: { available: 1, total: 2 }, uptime30d: { available: 1, total: 2 } } } } });
  });
  await signIn(page);
  await page.setViewportSize({ width: 1280, height: 800 });
  const probeCard = page.locator(".probe-card");
  await expect(probeCard).toHaveAccessibleName("Detalhes de API externa: Disponível, disponibilidade 100%");
  const zabbixCard = page.getByRole("button", { name: /Detalhes de Aplicação monitorada/ });
  await expect(probeCard).toBeVisible();
  const probeBox = await probeCard.boundingBox();
  const zabbixBox = await zabbixCard.boundingBox();
  expect(probeBox?.width).toBeLessThanOrEqual(230);
  expect(probeBox?.height).toBeCloseTo(120, 0);
  expect(zabbixBox?.width).toBeLessThanOrEqual(230);
  expect(zabbixBox?.height).toBeCloseTo(120, 0);
  await expect(page.locator(".block-uptime_list")).toHaveCSS("grid-column-start", "span 6");
  const row = page.locator(".uptime-row", { hasText: "API externa" });
  await expect(row.locator("rect")).toHaveCount(40);
  expect(await page.locator(".uptime-scroll").evaluate(element => element.scrollHeight > element.clientHeight)).toBe(true);
  await expect(probeCard.locator("rect")).toHaveCount(40);
  await row.click();
  await expect(page.getByRole("dialog")).toContainText("dia(s) restante(s)");
  await expect(page.getByRole("dialog")).toContainText("Uptime");
  await expect(page.locator(".probe-dialog .uptime-track rect")).toHaveCount(40);
  await expect(page.locator(".probe-dialog .uptime-track rect[opacity='0.35']")).toHaveCount(38);
  await expect(page.locator(".uptime-row", { hasText: "Aplicação 1" }).locator("rect")).toHaveCount(40);
  await expect.poll(() => ranges).toContain("24h");
  await page.getByRole("button", { name: "30 dias", exact: true }).click();
  await expect.poll(() => ranges).toContain("30d");
  await page.getByRole("button", { name: "7 dias", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Sem consultas neste período.");
  expect(ranges.every(range => ["24h", "7d", "30d"].includes(range))).toBe(true);
  await page.setViewportSize({ width: 390, height: 800 });
  await expect(row).toBeVisible();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await probeCard.click();
  await page.getByRole("link", { name: "Abrir em Aplicações", exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/aplicacoes$/);
  expect(new URL(page.url()).search).toBe("");
  await expect(page.locator(".app-monitor-detail h2")).toHaveText("API externa");
  await expect(page.locator(".app-monitor-item[aria-current=true]")).toContainText("API externa");
});
