import { test, expect } from "@playwright/test";
import { displayNamesFixture } from "../fixtures/display-names";
import { signIn } from "../fixtures/infrastructure";
import { asgardUrl } from "../../lib/infrastructure/navigation";

test("VM names preserve conflict drafts, refresh and restore with confirmation without Agent", async ({ page }) => {
  const state = await displayNamesFixture(page), vm = state.hosts[0].vms[0]; vm.linuxHostKey = null;
  await signIn(page); await page.goto("/admin/configuracoes");
  await page.getByRole("button", { name: "Editar nome " + vm.name, exact: true }).click();
  await page.getByLabel("Nome amigável da VM").fill("tpl Banco principal");
  state.conflict = true; await page.getByRole("button", { name: "Salvar nome", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "outra sessão" })).toBeVisible();
  await expect(page.getByLabel("Nome amigável da VM")).toHaveValue("tpl Banco principal");
  state.conflict = false; await page.getByRole("button", { name: "Salvar nome", exact: true }).click();
  await expect.poll(() => state.preferences.length).toBe(1); expect(state.admin.document.revision).toBe(1);
  await page.reload(); await expect(page.locator(".admin-vms")).toContainText("tpl Banco principal");
  await page.goto(asgardUrl(vm.parentHostKey, vm.vmKey, "7d"));
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Detalhes da VM · tpl Banco principal");
  await expect(page.getByLabel("Host ou VM do gráfico")).toHaveValue(vm.vmKey);
  await page.getByRole("button", { name: "Editar nome", exact: true }).click();
  await page.getByRole("button", { name: "Restaurar nome técnico", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Cancelar", exact: true }).click();
  expect(state.preferences[0].displayName).toBe("tpl Banco principal");
  await page.getByRole("button", { name: "Restaurar nome técnico", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Restaurar nome técnico", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Detalhes da VM · " + vm.name);
  expect(state.preferences[0].displayName).toBe(null); expect(page.url()).toContain("range=7d");
});
test("VM workload context reuses existing container config, saves alias without highlight and returns to same VM", async ({ page }) => {
  const state = await displayNamesFixture(page), vm = state.hosts[0].vms[0]; vm.linuxHostKey = "linux-operacao";
  const originalCount = state.admin.resources.length;
  await signIn(page); await page.goto(asgardUrl(vm.parentHostKey, vm.vmKey, "7d"));
  await page.getByRole("button", { name: "Serviços e containers de " + vm.name, exact: true }).click();
  await page.getByRole("dialog").getByRole("link", { name: "Editar configuração Serviço 2", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toHaveText("Recursos em destaque");
  expect(state.admin.writes.length).toBe(0);
  await expect(page.getByLabel("Nome amigável", { exact: true })).toHaveValue("Serviço 2");
  await page.getByLabel("Nome amigável", { exact: true }).fill("Aplicação da VM");
  await page.getByLabel("Descrição do serviço", { exact: true }).fill("Portal de atendimento");
  await page.getByLabel("Tipo do serviço", { exact: true }).fill("Front");
  await page.getByLabel("Configuração habilitada", { exact: true }).check();
  await page.getByLabel("Destacar no dashboard", { exact: true }).uncheck();
  await page.getByRole("button", { name: "Salvar recurso", exact: true }).click();
  await expect.poll(() => state.admin.writes.length).toBe(1);
  expect(state.admin.resources.length).toBe(originalCount);
  expect(state.admin.writes[0].body.context).toMatchObject({ vmKey: vm.vmKey, parentHostKey: vm.parentHostKey, containerReference: "workload-0" });
  await page.getByRole("link", { name: "Voltar ao contexto do recurso", exact: true }).click();
  await expect(page).toHaveURL(new RegExp("vm=" + vm.vmKey + ".*range=7d"));
  await page.goto("/servicos");
  await expect(page.locator(".container-table th[scope=row] > strong").filter({ hasText: "Aplicação da VM" })).toHaveCount(1);
  await page.getByRole("link", { name: "Editar configuração Aplicação da VM", exact: true }).click();
  await expect(page.getByLabel("Destacar no dashboard", { exact: true })).not.toBeChecked();
  await expect(page.getByLabel("Descrição do serviço", { exact: true })).toHaveValue("Portal de atendimento");
  await expect(page.getByLabel("Tipo do serviço", { exact: true })).toHaveValue("Front");
  await page.getByLabel("Destacar no dashboard", { exact: true }).check();
  await page.getByRole("button", { name: "Salvar recurso", exact: true }).click();
  await expect.poll(() => state.admin.resources.find(item => item.displayName === "Aplicação da VM")?.dashboardEnabled).toBe(true);
  expect(state.admin.resources.length).toBe(originalCount);
});
test("orphan VM preferences remain editable and unknown contexts never save", async ({ page }) => {
  const state = await displayNamesFixture(page), vm = state.hosts[0].vms[0], at = new Date().toISOString();
  state.preferences.push({ vmKey: vm.vmKey, hostKey: vm.parentHostKey, vmId: vm.vmId!, originalName: vm.name, displayName: "Preferência órfã", virtualizationType: "qemu", revision: 1, createdAt: at, updatedAt: at });
  state.hosts[0].vms = [];
  await signIn(page); await page.goto("/admin/configuracoes");
  await expect(page.locator(".admin-vms")).toContainText("Preferência sem descoberta atual");
  await page.getByRole("button", { name: "Editar nome Preferência órfã", exact: true }).click();
  await page.getByLabel("Nome amigável da VM").fill("Guardado sem descoberta");
  await page.getByRole("button", { name: "Salvar nome", exact: true }).click();
  await expect.poll(() => state.preferences[0].revision).toBe(2);
  await page.goto("/admin/recursos?hostKey=wrong&containerReference=workload-0&parentHostKey=ASGARD&vmKey=" + vm.vmKey);
  await expect(page.getByRole("alert").filter({ hasText: "alvo ou vínculo" })).toBeVisible();
  expect(state.admin.writes.length).toBe(1);
});
for (const width of [320, 390, 768, 1366, 1920, 3440]) test("long VM names fit " + width + "px", async ({ page }) => {
  const state = await displayNamesFixture(page), vm = state.hosts[0].vms[0], at = new Date().toISOString();
  state.preferences.push({ vmKey: vm.vmKey, hostKey: vm.parentHostKey, vmId: vm.vmId!, originalName: vm.name, displayName: "Aplicações e processamento ".repeat(5).slice(0, 120), virtualizationType: "qemu", revision: 1, createdAt: at, updatedAt: at });
  await page.setViewportSize({ width, height: width >= 1920 ? 1080 : 800 });
  await signIn(page); await page.goto(asgardUrl(vm.parentHostKey, vm.vmKey));
  await expect(page.getByRole("button", { name: "Editar nome", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.getByRole("button", { name: "Editar nome", exact: true }).click();
  await expect(page.getByLabel("Nome amigável da VM")).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: ".cache/names-vm-" + width + ".png", fullPage: width === 390 });
  await page.goto("/admin/configuracoes"); await page.locator(".admin-vms").scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: ".cache/names-admin-" + width + ".png" });
});
