import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import YAML from "yaml";
const read = path => readFileSync(new URL("../" + path, import.meta.url), "utf8");

for (const dev of [false, true]) {
  test((dev ? "dev" : "prod") + " stack isolates names, routing and storage", () => {
    const c = YAML.parse(read("docker/docker-compose" + (dev ? ".dev" : "") + ".yaml"));
    const web = dev ? "pulse-dev" : "pulse", db = dev ? "pulse_postgres_dev" : "pulse_postgres", cache = dev ? "pulse_redis_dev" : "pulse_redis";
    assert.equal(c.version, "3.8");
    assert.deepEqual(c.networks, { network_public: { external: true, name: "network_public" } });
    assert.deepEqual(Object.keys(c.services), [web, web + "-collector", web + "-probe", web + "-vps-monitor", web + "-signal-monitor", db, cache]);
    for (const [name, service] of Object.entries(c.services)) {
      assert.deepEqual(service.networks, ["network_public"]);
      assert.equal(service.ports, undefined);
      assert.equal(service.depends_on, undefined);
      assert.equal(service.deploy.replicas, 1);
      assert.deepEqual(service.deploy.placement.constraints, ["node.role == manager"]);
      assert.ok(service.deploy.resources.limits.memory);
      assert.ok(service.deploy.resources.reservations.memory);
      if (name !== web) assert.equal(service.deploy.labels, undefined);
    }
    const app = c.services[web];
    const image = "ghcr.io/softcominnovation/softcom-pulse:${PULSE_VERSION:-" + (dev ? "dev" : "latest") + "}";
    assert.equal(app.image, image);
    for (const suffix of ["-collector", "-probe", "-vps-monitor", "-signal-monitor"]) assert.equal(c.services[web + suffix].image, image);
    assert.equal(app.environment.API_BASE_URL, "${API_BASE_URL:-https://api.softcom.cloud}");
    assert.equal(app.environment.PULSE_EDITOR_EMAILS, "${PULSE_EDITOR_EMAILS:-}");
    assert.equal(app.environment.PULSE_PUBLIC_HOSTS, "${PULSE_PUBLIC_HOSTS:-}");
    assert.equal(c.services[web + "-collector"].environment.API_BASE_URL, "${API_BASE_URL:-https://api.softcom.cloud}");
    assert.equal(c.services[web + "-collector"].environment.PULSE_EDITOR_EMAILS, undefined);
    assert.equal(c.services[web + "-collector"].environment.PULSE_PUBLIC_HOSTS, undefined);
    assert.equal(c.services[web + "-probe"].environment.PULSE_EDITOR_EMAILS, undefined);
    assert.equal(c.services[web + "-probe"].environment.PULSE_PUBLIC_HOSTS, undefined);
    assert.equal(c.services[web + "-vps-monitor"].environment.PULSE_EDITOR_EMAILS, undefined);
    assert.equal(c.services[web + "-vps-monitor"].environment.PULSE_PUBLIC_HOSTS, undefined);
    assert.equal(c.services[web + "-signal-monitor"].environment.PULSE_EDITOR_EMAILS, undefined);
    assert.equal(c.services[web + "-signal-monitor"].environment.PULSE_PUBLIC_HOSTS, undefined);
    assert.ok(app.environment.REDIS_URL.includes(cache));
    assert.equal(c.services[web + "-collector"].deploy.update_config.order, "stop-first");
    assert.deepEqual(c.services[web + "-collector"].command, ["node", "--conditions=react-server", "collector/index.mjs"]);
    const probe = c.services[web + "-probe"];
    assert.deepEqual(probe.command, ["node", "--conditions=react-server", "collector/probe.mjs"]);
    assert.equal(probe.environment.PROBE_INTERVAL_MS, "${PROBE_INTERVAL_MS:-60000}");
    assert.equal(probe.environment.ZABBIX_API_URL, undefined);
    assert.equal(probe.environment.ZABBIX_API_TOKEN, undefined);
    assert.equal(probe.deploy.labels, undefined);
    const vps = c.services[web + "-vps-monitor"];
    assert.deepEqual(vps.command, ["node", "--conditions=react-server", "collector/vps-monitor.mjs"]);
    assert.equal(vps.environment.VPS_MONITOR_INTERVAL_MS, "${VPS_MONITOR_INTERVAL_MS:-60000}");
    assert.equal(vps.environment.ZABBIX_API_URL, undefined);
    assert.equal(vps.environment.ZABBIX_API_TOKEN, undefined);
    assert.equal(vps.deploy.labels, undefined);
    const signal = c.services[web + "-signal-monitor"];
    assert.deepEqual(signal.command, ["node", "--conditions=react-server", "collector/signal-monitor.mjs"]);
    assert.equal(signal.environment.SIGNAL_MONITOR_INTERVAL_MS, "${SIGNAL_MONITOR_INTERVAL_MS:-60000}");
    assert.equal(signal.environment.SIGNAL_API_BASE_URL, "${SIGNAL_API_BASE_URL:-}");
    assert.equal(signal.environment.SIGNAL_HEALTH_LIVE_PATH, "${SIGNAL_HEALTH_LIVE_PATH:-/health/live}");
    assert.equal(signal.environment.SIGNAL_HEALTH_READY_PATH, "${SIGNAL_HEALTH_READY_PATH:-/health/ready}");
    assert.equal(signal.environment.ZABBIX_API_URL, undefined);
    assert.equal(signal.environment.ZABBIX_API_TOKEN, undefined);
    assert.equal(signal.deploy.labels, undefined);
    assert.deepEqual(c.services[cache].command, ["redis-server", "--appendonly", "yes"]);
    assert.ok(c.services[db].environment.POSTGRES_PASSWORD.includes(dev ? "POSTGRES_PASSWORD_DEV:" : "POSTGRES_PASSWORD:"));
    assert.ok(app.deploy.labels.includes("traefik.http.routers." + web + ".tls.certresolver=letsencryptresolver"));
    assert.ok(app.deploy.labels.includes("traefik.http.routers." + web + ".entrypoints=websecure"));
    assert.ok(app.deploy.labels.some(label => label.includes("Host(`" + (dev ? "dev-" : "") + "pulse.softcomtecnologia.com`)")));
    assert.deepEqual(Object.keys(c.volumes), [db + "_data", cache + "_data"]);
  });
  test((dev ? "dev" : "prod") + " workflow only publishes from the correct tags", () => {
    const c = YAML.parse(read(".github/workflows/deploy-" + (dev ? "dev" : "prod") + ".yml"));
    assert.deepEqual(Object.keys(c.on), ["push"]);
    assert.deepEqual(Object.keys(c.on.push), ["tags"]);
    assert.deepEqual(c.on.push.tags, dev ? ["v*.*.*-dev"] : ["v*.*.*", "!*-*", "!*\\+*"]);
    assert.deepEqual(c.permissions, { contents: "read", packages: "write" });
    const steps = c.jobs.publish.steps;
    assert.ok(steps.find(step => step.run?.includes("validate-release.mjs " + (dev ? "development" : "production"))));
    const build = steps.find(step => step.uses?.startsWith("docker/build-push-action@"));
    assert.equal(build.with.platforms, "linux/amd64,linux/arm64");
    assert.equal(build.with.push, true);
    assert.equal(build.with["build-args"], undefined);
    const verification = steps.find(step => step.name === "Verify platforms and packaged runtime").run;
    assert.ok(verification.includes('docker buildx imagetools inspect "$image" --raw > manifest.json'));
    assert.ok(verification.includes('for arch in amd64 arm64; do'));
    assert.ok(verification.includes('platform_digest=$(node scripts/platform-digest.mjs manifest.json "$arch")'));
    assert.ok(verification.includes('--entrypoint node "$IMAGE@$platform_digest"'));
    assert.ok(verification.includes('["--conditions=react-server","collector/index.mjs","--check"]'));
    assert.ok(!verification.includes('--entrypoint node "$image"'));
    const tags = steps.find(step => step.uses?.startsWith("docker/metadata-action@")).with.tags;
    assert.equal(tags.includes("value=latest"), !dev);
    assert.equal(tags.includes("value=dev\n"), dev);
  });
}
test("entrypoint and build context preserve the runtime boundary", () => {
  const dockerfile = read("Dockerfile"), entrypoint = read("docker/entrypoint.sh");
  assert.ok(!entrypoint.includes("\r"));
  assert.match(entrypoint, /set -eu/);
  assert.ok(entrypoint.indexOf("node docker/migrate.mjs") < entrypoint.indexOf('exec "$@"'));
  assert.match(dockerfile, /USER node/);
  assert.match(dockerfile, /--chmod=755/);
  for (const part of ["runtime-dependencies", "/app/prisma", "/app/collector", "/app/node_modules"]) assert.ok(dockerfile.includes(part));
  for (const part of [".env*", ".git", "node_modules", ".next", "docs"]) assert.ok(read(".dockerignore").split(/\r?\n/).includes(part));
});
