"use client";

import { effectiveOptions, indicatorKeys, type PresentationBlock } from "@/lib/config/presentation";
import { Check, Field } from "./shared";

const labels: Record<string, string> = { name: "Nome", configured: "Ordem do recurso", state: "Estado", status: "Estado", health: "Healthcheck", cpu: "CPU (%)", memory: "Memória (%)", severity: "Severidade", recent: "Data de início", hosts: "Hosts", containers_running: "Containers em execução", containers_stopped: "Containers parados", problems: "Problemas", running: "Em execução", stopped: "Parado", paused: "Pausado", unknown: "Desconhecido" };
export function BlockOptionsEditor({ block, hosts, onChange }: { block: PresentationBlock; hosts: { hostKey: string; name: string }[]; onChange: (options: NonNullable<PresentationBlock["options"]>) => void }) {
  const options = { ...effectiveOptions({ type: block.type }), ...block.options } as NonNullable<PresentationBlock["options"]>;
  const set = (key: string, value: string | number | boolean | string[] | number[]) => onChange({ ...options, [key]: value });
  const checkList = (key: string, values: (string | number)[], names?: string[]) => <div className="admin-checks">{values.map((value, index) => <Check key={value} label={names?.[index] ?? labels[value] ?? String(value)}><input type="checkbox" checked={(options[key] as (string | number)[]).includes(value)} onChange={event => { const selected = options[key] as (string | number)[]; set(key, (event.target.checked ? [...selected, value] : selected.filter(item => item !== value)) as string[] | number[]); }} /></Check>)}</div>;
  if (block.type === "summary") return <fieldset><legend>Indicadores exibidos</legend>{checkList("indicators", [...indicatorKeys])}</fieldset>;
  if (block.type === "resource_card") return <p className="admin-muted">Métricas e estados seguem as preferências salvas do recurso.</p>;
  const sorts = block.type === "problems" ? ["severity", "recent"] : block.type === "highlighted_resources" ? ["configured", "name"] : block.type === "container_inventory" ? ["name", "status", "health", "cpu", "memory"] : ["name", "state", "cpu", "memory"];
  return <div className="admin-options"><div className="admin-fields"><Field label="Ordenar por"><select value={String(options.sortBy)} onChange={event => set("sortBy", event.target.value)}>{sorts.map(key => <option key={key} value={key}>{labels[key]}</option>)}</select></Field><Field label="Direção"><select value={String(options.sortDirection)} onChange={event => set("sortDirection", event.target.value)}><option value="asc">Crescente</option><option value="desc">Decrescente</option></select></Field><Field label={block.type === "highlighted_resources" ? "Fileiras visíveis" : "Linhas visíveis"} hint="Os demais itens continuam acessíveis por rolagem."><select value={Number(options.visibleRows)} onChange={event => set("visibleRows", Number(event.target.value))}>{Array.from({ length: block.type === "highlighted_resources" ? 3 : 8 }, (_, i) => i + (block.type === "highlighted_resources" ? 1 : 3)).map(value => <option key={value}>{value}</option>)}</select></Field></div>
    {options.sortBy === "health" && <p className="admin-muted">Crescente: falha, iniciando, saudável, sem healthcheck. Desconhecidos ficam sempre no fim.</p>}
    {options.sortBy === "state" && <p className="admin-muted">Crescente: execução, pausado, parado (VMs); disponível, indisponível (hosts). Desconhecidos ficam no fim.</p>}
    {block.type === "asgard_summary" && <fieldset><legend>Estados incluídos</legend>{checkList("states", ["running", "paused", "stopped", "unknown"])}</fieldset>}
    {block.type === "problems" && <fieldset><legend>Severidades incluídas</legend>{checkList("severities", [0, 1, 2, 3, 4, 5], ["Não classificado", "Informação", "Atenção", "Média", "Alta", "Desastre"])}</fieldset>}
    {block.type === "highlighted_resources" && <Check label="Somente recursos críticos"><input type="checkbox" checked={!!options.criticalOnly} onChange={event => set("criticalOnly", event.target.checked)} /></Check>}
    {block.type === "container_inventory" && <fieldset><legend>Hosts dos containers</legend><Check label="Todos os hosts"><input type="checkbox" checked={options.hostKeys === undefined} onChange={event => { if (event.target.checked) { const next = { ...options }; delete next.hostKeys; onChange(next); } else set("hostKeys", []); }} /></Check>{options.hostKeys !== undefined && <div className="admin-checks">{[...new Map([...hosts, ...(options.hostKeys as string[]).filter(key => !hosts.some(host => host.hostKey === key)).map(hostKey => ({ hostKey, name: `${hostKey} · sem descoberta atual` }))].map(item => [item.hostKey, item])).values()].map(host => <Check key={host.hostKey} label={host.name}><input type="checkbox" checked={(options.hostKeys as string[]).includes(host.hostKey)} onChange={event => set("hostKeys", event.target.checked ? [...options.hostKeys as string[], host.hostKey] : (options.hostKeys as string[]).filter(key => key !== host.hostKey))} /></Check>)}</div>}</fieldset>}
  </div>;
}
